// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: proto/hub.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	HubId         string                 `protobuf:"bytes,2,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *RegisterResponse) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Topics        []string               `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	SourceModules []string               `protobuf:"bytes,3,rep,name=source_modules,json=sourceModules,proto3" json:"source_modules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *SubscribeRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *SubscribeRequest) GetSourceModules() []string {
	if x != nil {
		return x.SourceModules
	}
	return nil
}

type CrossQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceModule  string                 `protobuf:"bytes,1,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`
	TargetModule  string                 `protobuf:"bytes,2,opt,name=target_module,json=targetModule,proto3" json:"target_module,omitempty"`
	Query         *QueryRequest          `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossQueryRequest) Reset() {
	*x = CrossQueryRequest{}
	mi := &file_proto_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossQueryRequest) ProtoMessage() {}

func (x *CrossQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossQueryRequest.ProtoReflect.Descriptor instead.
func (*CrossQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{3}
}

func (x *CrossQueryRequest) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *CrossQueryRequest) GetTargetModule() string {
	if x != nil {
		return x.TargetModule
	}
	return ""
}

func (x *CrossQueryRequest) GetQuery() *QueryRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type CrossExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceModule  string                 `protobuf:"bytes,1,opt,name=source_module,json=sourceModule,proto3" json:"source_module,omitempty"`
	TargetModule  string                 `protobuf:"bytes,2,opt,name=target_module,json=targetModule,proto3" json:"target_module,omitempty"`
	Request       *ExecuteRequest        `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrossExecuteRequest) Reset() {
	*x = CrossExecuteRequest{}
	mi := &file_proto_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrossExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossExecuteRequest) ProtoMessage() {}

func (x *CrossExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossExecuteRequest.ProtoReflect.Descriptor instead.
func (*CrossExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_hub_proto_rawDescGZIP(), []int{4}
}

func (x *CrossExecuteRequest) GetSourceModule() string {
	if x != nil {
		return x.SourceModule
	}
	return ""
}

func (x *CrossExecuteRequest) GetTargetModule() string {
	if x != nil {
		return x.TargetModule
	}
	return ""
}

func (x *CrossExecuteRequest) GetRequest() *ExecuteRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

var File_proto_hub_proto protoreflect.FileDescriptor

const file_proto_hub_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/hub.proto\x12\x06nekkus\x1a\x12proto/module.proto\"\xbc\x01\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\x06hub_id\x18\x02 \x01(\tR\x05hubId\x12<\n" +
	"\x06config\x18\x03 \x03(\v2$.nekkus.RegisterResponse.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"v\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x16\n" +
	"\x06topics\x18\x02 \x03(\tR\x06topics\x12%\n" +
	"\x0esource_modules\x18\x03 \x03(\tR\rsourceModules\"\x89\x01\n" +
	"\x11CrossQueryRequest\x12#\n" +
	"\rsource_module\x18\x01 \x01(\tR\fsourceModule\x12#\n" +
	"\rtarget_module\x18\x02 \x01(\tR\ftargetModule\x12*\n" +
	"\x05query\x18\x03 \x01(\v2\x14.nekkus.QueryRequestR\x05query\"\x91\x01\n" +
	"\x13CrossExecuteRequest\x12#\n" +
	"\rsource_module\x18\x01 \x01(\tR\fsourceModule\x12#\n" +
	"\rtarget_module\x18\x02 \x01(\tR\ftargetModule\x120\n" +
	"\arequest\x18\x03 \x01(\v2\x16.nekkus.ExecuteRequestR\arequest2\xc9\x02\n" +
	"\tNekkusHub\x128\n" +
	"\bRegister\x12\x12.nekkus.ModuleInfo\x1a\x18.nekkus.RegisterResponse\x12:\n" +
	"\fPublishEvent\x12\x11.nekkus.DataEvent\x1a\x17.nekkus.PublishResponse\x12@\n" +
	"\x0fSubscribeEvents\x12\x18.nekkus.SubscribeRequest\x1a\x11.nekkus.DataEvent0\x01\x12>\n" +
	"\n" +
	"CrossQuery\x12\x19.nekkus.CrossQueryRequest\x1a\x15.nekkus.QueryResponse\x12D\n" +
	"\fCrossExecute\x12\x1b.nekkus.CrossExecuteRequest\x1a\x17.nekkus.ExecuteResponseB0Z.github.com/GalitskyKK/nekkus-core/pkg/protocolb\x06proto3"

var (
	file_proto_hub_proto_rawDescOnce sync.Once
	file_proto_hub_proto_rawDescData []byte
)

func file_proto_hub_proto_rawDescGZIP() []byte {
	file_proto_hub_proto_rawDescOnce.Do(func() {
		file_proto_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hub_proto_rawDesc), len(file_proto_hub_proto_rawDesc)))
	})
	return file_proto_hub_proto_rawDescData
}

var file_proto_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_hub_proto_goTypes = []any{
	(*RegisterResponse)(nil),    // 0: nekkus.RegisterResponse
	(*PublishResponse)(nil),     // 1: nekkus.PublishResponse
	(*SubscribeRequest)(nil),    // 2: nekkus.SubscribeRequest
	(*CrossQueryRequest)(nil),   // 3: nekkus.CrossQueryRequest
	(*CrossExecuteRequest)(nil), // 4: nekkus.CrossExecuteRequest
	nil,                         // 5: nekkus.RegisterResponse.ConfigEntry
	(*QueryRequest)(nil),        // 6: nekkus.QueryRequest
	(*ExecuteRequest)(nil),      // 7: nekkus.ExecuteRequest
	(*ModuleInfo)(nil),          // 8: nekkus.ModuleInfo
	(*DataEvent)(nil),           // 9: nekkus.DataEvent
	(*QueryResponse)(nil),       // 10: nekkus.QueryResponse
	(*ExecuteResponse)(nil),     // 11: nekkus.ExecuteResponse
}
var file_proto_hub_proto_depIdxs = []int32{
	5,  // 0: nekkus.RegisterResponse.config:type_name -> nekkus.RegisterResponse.ConfigEntry
	6,  // 1: nekkus.CrossQueryRequest.query:type_name -> nekkus.QueryRequest
	7,  // 2: nekkus.CrossExecuteRequest.request:type_name -> nekkus.ExecuteRequest
	8,  // 3: nekkus.NekkusHub.Register:input_type -> nekkus.ModuleInfo
	9,  // 4: nekkus.NekkusHub.PublishEvent:input_type -> nekkus.DataEvent
	2,  // 5: nekkus.NekkusHub.SubscribeEvents:input_type -> nekkus.SubscribeRequest
	3,  // 6: nekkus.NekkusHub.CrossQuery:input_type -> nekkus.CrossQueryRequest
	4,  // 7: nekkus.NekkusHub.CrossExecute:input_type -> nekkus.CrossExecuteRequest
	0,  // 8: nekkus.NekkusHub.Register:output_type -> nekkus.RegisterResponse
	1,  // 9: nekkus.NekkusHub.PublishEvent:output_type -> nekkus.PublishResponse
	9,  // 10: nekkus.NekkusHub.SubscribeEvents:output_type -> nekkus.DataEvent
	10, // 11: nekkus.NekkusHub.CrossQuery:output_type -> nekkus.QueryResponse
	11, // 12: nekkus.NekkusHub.CrossExecute:output_type -> nekkus.ExecuteResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_hub_proto_init() }
func file_proto_hub_proto_init() {
	if File_proto_hub_proto != nil {
		return
	}
	file_proto_module_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hub_proto_rawDesc), len(file_proto_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hub_proto_goTypes,
		DependencyIndexes: file_proto_hub_proto_depIdxs,
		MessageInfos:      file_proto_hub_proto_msgTypes,
	}.Build()
	File_proto_hub_proto = out.File
	file_proto_hub_proto_goTypes = nil
	file_proto_hub_proto_depIdxs = nil
}
