// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: proto/hub.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NekkusHub_Register_FullMethodName        = "/nekkus.NekkusHub/Register"
	NekkusHub_PublishEvent_FullMethodName    = "/nekkus.NekkusHub/PublishEvent"
	NekkusHub_SubscribeEvents_FullMethodName = "/nekkus.NekkusHub/SubscribeEvents"
	NekkusHub_CrossQuery_FullMethodName      = "/nekkus.NekkusHub/CrossQuery"
	NekkusHub_CrossExecute_FullMethodName    = "/nekkus.NekkusHub/CrossExecute"
)

// NekkusHubClient is the client API for NekkusHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NekkusHubClient interface {
	Register(ctx context.Context, in *ModuleInfo, opts ...grpc.CallOption) (*RegisterResponse, error)
	PublishEvent(ctx context.Context, in *DataEvent, opts ...grpc.CallOption) (*PublishResponse, error)
	SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataEvent], error)
	CrossQuery(ctx context.Context, in *CrossQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	CrossExecute(ctx context.Context, in *CrossExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type nekkusHubClient struct {
	cc grpc.ClientConnInterface
}

func NewNekkusHubClient(cc grpc.ClientConnInterface) NekkusHubClient {
	return &nekkusHubClient{cc}
}

func (c *nekkusHubClient) Register(ctx context.Context, in *ModuleInfo, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, NekkusHub_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nekkusHubClient) PublishEvent(ctx context.Context, in *DataEvent, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, NekkusHub_PublishEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nekkusHubClient) SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DataEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NekkusHub_ServiceDesc.Streams[0], NekkusHub_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, DataEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NekkusHub_SubscribeEventsClient = grpc.ServerStreamingClient[DataEvent]

func (c *nekkusHubClient) CrossQuery(ctx context.Context, in *CrossQueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, NekkusHub_CrossQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nekkusHubClient) CrossExecute(ctx context.Context, in *CrossExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, NekkusHub_CrossExecute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NekkusHubServer is the server API for NekkusHub service.
// All implementations must embed UnimplementedNekkusHubServer
// for forward compatibility.
type NekkusHubServer interface {
	Register(context.Context, *ModuleInfo) (*RegisterResponse, error)
	PublishEvent(context.Context, *DataEvent) (*PublishResponse, error)
	SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[DataEvent]) error
	CrossQuery(context.Context, *CrossQueryRequest) (*QueryResponse, error)
	CrossExecute(context.Context, *CrossExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedNekkusHubServer()
}

// UnimplementedNekkusHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNekkusHubServer struct{}

func (UnimplementedNekkusHubServer) Register(context.Context, *ModuleInfo) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNekkusHubServer) PublishEvent(context.Context, *DataEvent) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishEvent not implemented")
}
func (UnimplementedNekkusHubServer) SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[DataEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedNekkusHubServer) CrossQuery(context.Context, *CrossQueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrossQuery not implemented")
}
func (UnimplementedNekkusHubServer) CrossExecute(context.Context, *CrossExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrossExecute not implemented")
}
func (UnimplementedNekkusHubServer) mustEmbedUnimplementedNekkusHubServer() {}
func (UnimplementedNekkusHubServer) testEmbeddedByValue()                   {}

// UnsafeNekkusHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NekkusHubServer will
// result in compilation errors.
type UnsafeNekkusHubServer interface {
	mustEmbedUnimplementedNekkusHubServer()
}

func RegisterNekkusHubServer(s grpc.ServiceRegistrar, srv NekkusHubServer) {
	// If the following call panics, it indicates UnimplementedNekkusHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NekkusHub_ServiceDesc, srv)
}

func _NekkusHub_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModuleInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NekkusHubServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NekkusHub_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NekkusHubServer).Register(ctx, req.(*ModuleInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NekkusHub_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NekkusHubServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NekkusHub_PublishEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NekkusHubServer).PublishEvent(ctx, req.(*DataEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _NekkusHub_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NekkusHubServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeRequest, DataEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NekkusHub_SubscribeEventsServer = grpc.ServerStreamingServer[DataEvent]

func _NekkusHub_CrossQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NekkusHubServer).CrossQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NekkusHub_CrossQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NekkusHubServer).CrossQuery(ctx, req.(*CrossQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NekkusHub_CrossExecute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NekkusHubServer).CrossExecute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NekkusHub_CrossExecute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NekkusHubServer).CrossExecute(ctx, req.(*CrossExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NekkusHub_ServiceDesc is the grpc.ServiceDesc for NekkusHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NekkusHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nekkus.NekkusHub",
	HandlerType: (*NekkusHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _NekkusHub_Register_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _NekkusHub_PublishEvent_Handler,
		},
		{
			MethodName: "CrossQuery",
			Handler:    _NekkusHub_CrossQuery_Handler,
		},
		{
			MethodName: "CrossExecute",
			Handler:    _NekkusHub_CrossExecute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _NekkusHub_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/hub.proto",
}
